// Generated by CoffeeScript 2.5.1
(function() {
  var BigNumber, instagramIdToUrlSegment, urlSegmentToInstagramId;

  BigNumber = require('bignumber.js');

  BigNumber.config({
    ALPHABET: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789$_'
  });

  instagramIdToUrlSegment = function(id) {
    if (typeof id === 'number' && id > Number.MAX_SAFE_INTEGER) {
      throw 'Input value too large, please pass as string';
    }
    return (new BigNumber(id)).toString(64).replace(/\$/g, '-');
  };

  urlSegmentToInstagramId = function(urlSegment) {
    return (new BigNumber(urlSegment.replace(/-/g, '$'), 64)).toString(10);
  };

  module.exports = {instagramIdToUrlSegment, urlSegmentToInstagramId};

}).call(this);
